package:
  name: io3d
  version: "1.0.36"

source:
# this is used for build from git hub
  git_rev: 1.0.36
  git_url: https://github.com/mjirik/io3d.git

# this is used for pypi 
  # fn: io3d-1.0.36.tar.gz
  # url: https://pypi.python.org/packages/source/i/io3d/io3d-1.0.36.tar.gz
  # md5: a3ce512c4c97ac2410e6dcc96a801bd8
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - io3d = io3d:main
    #
    # Would create an entry point called io3d that calls io3d.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - pydicom
    - pyyaml

  run:
    - python
    - numpy
    - scipy
    - pydicom
    - pyyaml

test:
  # Python imports
  imports:
    - io3d

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mjirik/io3d
  license: BSD License
  summary: '3D data read and write'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
